Algoritmo "EXC24L02"
//
//
// Descrição   : Solicitar o nome e a idade de 3 pessoas (utilizando a estrutura PARA).
// Autor(a)    : Fellipe Miquelão Schmidt - R.A.: 25153218-2
// Data atual  : 23/08/2025
Var

   x, idade: inteiro
   nome: caractere


inicio

   para x de 1 ate 3 faca

      escreva ("Digite o nome da ", x, "ª pessoa: ")
      leia (nome)
      escreva ("Digite a idade da ", x, "ª pessoa: ")
      leia (idade)

   fimpara

fimalgoritmo