Algoritmo "EXC30L02"
//
//
// Descrição   : Apresentar todos os números ímpares entre 5 e 50, um ao lado do outro (utilizando PARA).
// Autor(a)    : Fellipe Miquelão Schmidt - R.A.: 25153218-2
// Data atual  : 23/08/2025
Var

   cont: inteiro

inicio

   escreval ("== DEMONSTRADOR DE NÚMEROS PARES ENTRE 5 E 50 ==")
   escreva (" ")
   escreva(" ")



   para cont de 6 ate 50 passo 2 faca

      escreva (cont)

   fimpara


fimalgoritmo